### ISSUE TITLE
Auto node failed with error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/auto-node#15]
We have seen this happening for at least 3 users @Daniel-VDM:

```
 ./auto_node.sh status
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Auto node failed with error: Expecting value: line 1 column 1 (char 0)

Waiting for network response before raising exception for daemon restart.

```

**Comment by yelllowsin** [comment]
Left it running for some more time, it seems it cannot activate the node anymore, though the blockchain seems to be syncing:

```
./auto_node.sh status
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Auto node failed with error: Expecting value: line 1 column 1 (char 0)

Waiting for network response before raising exception for daemon restart.
tail: /home/yelllowsin/.hmy/autonode_monitor.log: file truncated
[!] https://api.s0.os.hmny.io/ is alive!
[!] https://api.s0.os.hmny.io/ is alive!
[!] https://api.s3.os.hmny.io is alive!
[!] http://localhost:9500/ is alive!
Validator Address: one1t46czjhc6ezjp6ce872ld7krdt70sz3gv5cxc5
EPOS status: not eligible to be elected next epoch
Booted status: manually turned inactive or insufficient uptime
Current epoch performance: null
Node not active, reactivating...
Node not synced, did NOT activate node.
This node's latest header at 2020-04-18 13:57:16.653565: {
    "beacon-chain-header": {
        "shard-id": 0,
        "block-header-hash": "0x1b5c6929728c3775425bef29c37356a30de395f391cbb398ec7451b7b495a5ad",
        "block-number": 37213,
        "view-id": 37213,
        "epoch": 979
    },
    "shard-chain-header": {
        "shard-id": 3,
        "block-header-hash": "0x6b6772ff1c0169d94a2472ed285222df203cc45b1ab771a16336014f4199c68a",
        "block-number": 39574,
        "view-id": 39574,
        "epoch": 979
    }
}
Validator Address: one1t46czjhc6ezjp6ce872ld7krdt70sz3gv5cxc5
EPOS status: not eligible to be elected next epoch
Booted status: manually turned inactive or insufficient uptime
Current epoch performance: null
Node not active, reactivating...
Node not synced, did NOT activate node.
This node's latest header at 2020-04-18 13:57:26.140085: {
    "beacon-chain-header": {
        "shard-id": 0,
        "block-header-hash": "0x72ab5cd8156ac532ef1a9b0530429d1f76df855376e7fe740a0906f780ed74a0",
        "block-number": 37215,
        "view-id": 37215,
        "epoch": 979
    },
    "shard-chain-header": {
        "shard-id": 3,
        "block-header-hash": "0x704056d29d8a2990ccd10ec0f1b1928e7d2280a849c12a7c12229f1dd9544f24",
        "block-number": 39576,
        "view-id": 39576,
        "epoch": 979
    }
}
Validator Address: one1t46czjhc6ezjp6ce872ld7krdt70sz3gv5cxc5
EPOS status: not eligible to be elected next epoch
Booted status: manually turned inactive or insufficient uptime
Current epoch performance: null
Node not active, reactivating...
Node not synced, did NOT activate node.
This node's latest header at 2020-04-18 13:57:35.618612: {
    "beacon-chain-header": {
        "shard-id": 0,
        "block-header-hash": "0xbf4f966fb7900a554d6481912eac0787e1275318124258fe23707ac654c0d841",
        "block-number": 37216,
        "view-id": 37216,
        "epoch": 979
    },
    "shard-chain-header": {
        "shard-id": 3,
        "block-header-hash": "0x782ca09c688afa6b19fa4126b01a28198d0ff9d2e930a2e0fcfd67a65136daed",
        "block-number": 39577,
        "view-id": 39577,
        "epoch": 979
    }
}
Validator Address: one1t46czjhc6ezjp6ce872ld7krdt70sz3gv5cxc5
Traceback (most recent call last):
  File "/home/yelllowsin/.local/lib/python3.6/site-packages/AutoNode/monitor.py", line 87, in start
    _run_monitor(shard_endpoint)
  File "/home/yelllowsin/.local/lib/python3.6/site-packages/AutoNode/monitor.py", line 62, in _run_monitor
    all_val = get_all_validator_addresses(node_config['endpoint'])
  File "/home/yelllowsin/.local/lib/python3.6/site-packages/AutoNode/blockchain.py", line 89, in get_all_validator_addresses
    body = json.loads(response.content)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Auto node failed with error: Expecting value: line 1 column 1 (char 0)

Waiting for network response before raising exception for daemon restart.

```

**Comment by danbedford** [comment]
+1 I'm seeing this exact issue too:

```
harmony@junglecity-pangaeaOSTN-S0:~$ ./auto_node.sh status
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Auto node failed with error: Expecting value: line 1 column 1 (char 0)

Waiting for network response before raising exception for daemon restart.
```

**Comment by danbedford** [comment]
I tried killing the autonode and restarting without the --clean flag (so as to not have to re-sync the entire chain) and it seems to be stuck at `[!] https://api.s0.os.hmny.io/ is alive!` after responding "no" to adding the BLS key to the val:

```
harmony@junglecity-pangaeaOSTN-S0:~$ ./auto_node.sh kill
[sudo] password for harmony: 
harmony@junglecity-pangaeaOSTN-S0:~$ ./auto_node.sh run --auto-active --auto-reset
Enter wallet passphrase for one1njyvqvw3jq2klrl77udzuj4xlh8tslgj434urs
> 
Enter passphrase for all 1 imported BLS keys
> 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Saved Validator Information: {
    "validator-addr": "one1njyvqvw3jq2klrl77udzuj4xlh8tslgj434urs",
    "name": "JungleCity",
    "website": "junglecity.tech",
    "security-contact": "@danbedford on Telegram",
    "identity": "JungleCity Identity",
    "amount": 10100,
    "min-self-delegation": 10000,
    "rate": 0.12,
    "max-rate": 0.75,
    "max-change-rate": 0.01,
    "max-total-delegation": 10000000000.0,
    "details": "JungleCity :: Harmony Foundational Node Validator"
}
Saved Node Information: {
    "endpoint": "https://api.s0.os.hmny.io/",
    "network": "staking",
    "clean": false,
    "duration": null,
    "shard": null,
    "auto-reset": true,
    "auto-active": true,
    "no-validator": false,
    "public-bls-keys": [
        "e45e6b2282c01af3a1f8ed7190a387e04ff0dd660ce1b5a1fe7dc88df2a8436293a619a079c74c66897eeefb34b04414"
    ]
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AutoNode has been initialized!
[AutoNode] Initilized service...
Create validator config: {
    "validator-addr": "one1njyvqvw3jq2klrl77udzuj4xlh8tslgj434urs",
    "name": "JungleCity",
    "website": "junglecity.tech",
    "security-contact": "@danbedford on Telegram",
    "identity": "JungleCity Identity",
    "amount": 10100,
    "min-self-delegation": 10000,
    "rate": 0.12,
    "max-rate": 0.75,
    "max-change-rate": 0.01,
    "max-total-delegation": 10000000000.0,
    "details": "JungleCity :: Harmony Foundational Node Validator"
}
Using BLS key(s): ['e45e6b2282c01af3a1f8ed7190a387e04ff0dd660ce1b5a1fe7dc88df2a8436293a619a079c74c66897eeefb34b04414']
Waiting for https://api.s0.os.hmny.io/ to respond, tried 3 times
[!] https://api.s0.os.hmny.io/ is alive!
one1njyvqvw3jq2klrl77udzuj4xlh8tslgj434urs already in list of validators!
Add BLS key(s) to existing validator? [Y]/n 
> n
You entered: `n`
[!] https://api.s0.os.hmny.io/ is alive!
^Z
[5]+  Stopped                 ./auto_node.sh run --auto-active --auto-reset
harmony@junglecity-pangaeaOSTN-S0:~$ ./auto_node.sh status
[!] https://api.s0.os.hmny.io/ is alive!
^Z
[6]+  Stopped                 ./auto_node.sh status
```

**Comment by BrunoMarshall** [comment]
same here:
Auto node failed with error: Bad CLI args: hmy staking edit-validator --validator-addr one1arncr7cw6m606ygvde007mka03m72mnqutz0jx --active true --node https://api.s0.os.hmny.io/ --passphrase-file /root/.hmy/.wallet_pass 
        Exception: Command '['/root/.hmy/bin/hmy', 'staking', 'edit-validator', '--validator-addr', 'one1arncr7cw6m606ygvde007mka03m72mnqutz0jx', '--active', 'true', '--node', 'https://api.s0.os.hmny.io/', '--passphrase-file', '/root/.hmy/.wallet_pass']' returned non-zero exit status 1

**Comment by danbedford** [comment]
My node is back up and running automatically after Shard 0 was fixed, so it seems as tho it was a network problem and not an autonode problem, is that correct @fxfactorial?

**Comment by fxfactorial** [comment]
it was a downstream problem - look at the error, its because ofa timeout from the network - shard 0 was down for a litttle bit and hence couldn't process transactions

**Comment by JB273** [comment]
My node was also stuck in this error, but after restarting the service manually with;
`systemctl restart autonoded.service` it started working again.
